sudo: false
language: python
cache:
    directories:
        - "$HOME/.pyenv"
python:
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install mypy"

# command to run tests
script:
    - mypy --python-version 3.6 --check-untyped-defs --warn-redundant-casts --strict-optional --inferstats --no-warn-no-return --package sqlite
    - python -m unittest discover sqlite
    - pip install git+https://github.com/nl253/SQLiteREPL.git@dev && sqlite

# blocklist
branches:
    only:
        - dev

notifications:
    email: false

# vim: nowrap
